// <auto-generated />
using System;
using Lookups.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lookups.Data.Migrations
{
    [DbContext(typeof(LookupsContext))]
    partial class LookupsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lookups.Data.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameFl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameSl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5c60f693-bef5-e011-a485-80ee7300c695"),
                            CreatedDate = new DateTime(2022, 3, 11, 15, 42, 27, 847, DateTimeKind.Local).AddTicks(9139),
                            IsDelete = false,
                            NameFl = "Egypt",
                            NameSl = "مصر"
                        },
                        new
                        {
                            Id = new Guid("5c60f693-bef5-e011-a485-80ee7300c696"),
                            CreatedDate = new DateTime(2022, 3, 11, 15, 42, 27, 849, DateTimeKind.Local).AddTicks(2154),
                            IsDelete = false,
                            NameFl = "Kuwait",
                            NameSl = "الكويت"
                        });
                });

            modelBuilder.Entity("Lookups.Data.Entities.Gender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenderNameFl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GenderNameSl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShown")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Gender");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1160f693-bef5-e011-a485-80ee7300c611"),
                            CreatedDate = new DateTime(2022, 3, 11, 15, 42, 27, 851, DateTimeKind.Local).AddTicks(8129),
                            GenderNameFl = "Male",
                            GenderNameSl = "ذكر",
                            IsDelete = false,
                            IsShown = true
                        },
                        new
                        {
                            Id = new Guid("5160f693-bef5-e011-a485-80ee7300c612"),
                            CreatedDate = new DateTime(2022, 3, 11, 15, 42, 27, 853, DateTimeKind.Local).AddTicks(2246),
                            GenderNameFl = "Female",
                            GenderNameSl = "أنثي",
                            IsDelete = false,
                            IsShown = true
                        },
                        new
                        {
                            Id = new Guid("2260f693-bef5-e011-a485-80ee7300c693"),
                            CreatedDate = new DateTime(2022, 3, 11, 15, 42, 27, 853, DateTimeKind.Local).AddTicks(3052),
                            GenderNameFl = "Both",
                            GenderNameSl = "كلاهما",
                            IsDelete = false,
                            IsShown = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
